services:
    enm.transformer.service:
        class: ENM\TransformerBundle\Manager\TransformerManager
        arguments: [ @service_container ]

    enm.transformer.event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher