
parameters:
    enm.transformer.class: Enm\TransformerBundle\Manager\TransformerManager
    enm.transformer.event_dispatcher.class: Symfony\Component\EventDispatcher\EventDispatcher

services:
    enm.transformer:
        class: %enm.transformer.class%
        arguments: [ @enm.transformer.event_dispatcher, @enm.transformer.validator, @enm.transformer.assetic.parameter_bag ]

    enm.transformer.event_dispatcher:
        class: %enm.transformer.event_dispatcher.class%
    
    enm.transformer.validator:
        alias: validator
        
    enm.transformer.assetic.parameter_bag:
        alias: assetic.parameter_bag
