services:
    enm.transformer.service:
        class: ENM\TransformerBundle\Manager\TransformerManager
        arguments: [ @service_container ]

    enm.transformer.configuration.manager:
        class: ENM\TransformerBundle\Manager\ConfigurationManager
        arguments: [ @event_dispatcher ]