services:
    enm.transformer.service:
        class: ENM\TransformerBundle\Manager\TransformerManager
        arguments: [ @enm.transformer.event_dispatcher, @validator, @assetic.parameter_bag, @debug.stopwatch ]

    enm.transformer.listener.exception:
        class: ENM\TransformerBundle\Listener\ExceptionListener

    enm.transformer.event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        calls:
            - ["addListener", [transformer.event.on.exception, [@enm.transformer.listener.exception, onException]]]