services:
    enm.array.transformer.service:
        class: ENM\TransformerBundle\Manager\ArrayTransformerManager
    enm.json.transformer.service:
        class: ENM\TransformerBundle\Manager\JsonTransformerManager

    enm.transformer.service:
        class: ENM\TransformerBundle\Manager\TransformerManager

